# Generated by Django 5.2.3 on 2025-06-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='suQsYHqF', editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
